# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f469a43efea29210853c67ecabdff6da6945027ed8cb97cff8c05b0fb1b1a97b708438117468e45a880b1daa7a22c15a0443fe1e3cc044feabb311ab399f002

test:
  secret_key_base: b59f73ddc9f1b6307d245e0f54a1f605a26bc5462c4735c7f7f2ee1d86e396428488fddefdffc468ab580851a58ffc6351290387b31d11eff8cf12800b33e04a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
